version: '3'

services:
  apache:
    #image: 'php:7.4-apache'
    build:
        context: .
        dockerfile: Dockerfile-apache
    container_name: appserver
    restart: always
    ports:
      - '8080:80'
    volumes:
        - ./app:/var/www/html/
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: dbserver
    image: mysql:8.0
    cap_add:
        - SYS_NICE
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
